### ISSUE TITLE
The List

### ISSUE THREAD

**Issue by Sainan** [calamity-inc/universal-analog-plugin#1]
## Keyboards with a usable analogue interface

- Wooting
- Razer (Synapse must be installed and running)
  - Razer Huntsman V2 Analog
  - Razer Huntsman Mini Analog
  - Razer Huntsman V3 Pro
  - Razer Huntsman V3 Pro Mini
  - Razer Huntsman V3 Pro Tenkeyless
- NuPhy (Personally only tested Field75 HE, but all should work.)
- DrunkDeer (Personally only tested A75, but all should work.)
- Keychron
  - Keychron Q1 HE (Needs [custom firmware](https://analogsense.org/firmware/) for smoothest experience)
  - Keychron Q3 HE (Needs [custom firmware](https://analogsense.org/firmware/) for smoothest experience)
  - Keychron Q5 HE (Needs [custom firmware](https://analogsense.org/firmware/) for smoothest experience)
  - Keychron K2 HE (Needs [custom firmware](https://analogsense.org/firmware/) for smoothest experience)
  - Lemokey P1 HE (Needs [custom firmware](https://analogsense.org/firmware/) for smoothest experience)
- Madlions
  - MAD60HE
  - MAD68HE
  - MAD68R

## Keyboards that could possibly have a usable analogue interface

- Razer
  - Taratrus Pro (pre-existing art, tho it was not PR'd: https://github.com/DenkiSuki/Soup/commit/2ef6356d45c9e2ebad3f3fcaa021879ff4546d23)
- Madlions
  - Nano 68 Pro (apparently this one doesn't "just work", as reported in https://github.com/AnalogSense/universal-analog-plugin/issues/10)
  - 68 Pro R (apparently this one doesn't "just work", as reported in https://github.com/AnalogSense/universal-analog-plugin/issues/11)
- FinalMouse
  - [FinalMouse Centerpiece](https://finalmouse.com/products/centerpiece-overview) ("Coming soon")
- Flux
  - [Flux Keyboard](https://fluxkeyboard.com/?v=f0aa03aaca95) ("Coming soon")
- Pwnage
  - https://pwnage.com/products/zenblade-65
- MonsGeek (The software looks promising: https://github.com/AnalogSense/universal-analog-plugin/issues/25)
  - [MG75S HE](https://www.monsgeek.com/product/mg75s-he-fully-assembled-magnetic-switch-keyboard/)
  - [M1 V5 TMR](https://www.monsgeek.com/keyboard/m1-v5-tmr-fully-assembled/)
- MCHOSE
  - [Ace 68 Air HE](https://www.mchose.store/products/mchose-ace-68-air-hall-effect-magnetic-switch-gaming-keyboard) (Brought to my attention via https://github.com/AnalogSense/universal-analog-plugin/issues/20)
  - Jet 75HE (Brought to my attention via https://github.com/AnalogSense/universal-analog-plugin/issues/29)
- Ajazz (The software looks promising: https://github.com/AnalogSense/universal-analog-plugin/issues/23, https://github.com/AnalogSense/universal-analog-plugin/issues/24)
  - AK680
  - AK680 MAX
- Gamakay (Brought to my attention via https://github.com/AnalogSense/universal-analog-plugin/issues/27)
  - [NaughShark NS68 Hall Effect](https://gamakay.com/en-gb/products/gamakay-x-naughshark-ns68-8k-polling-rate-0-01mm-rt-accuracy-hall-effect-magnetic-keyboard)
- Lamzu (The software looks pretty barebones, and there's no way to see how far down a key is being pressed.)
  - Atlantis Pro
- Highground (Doesn't look like they have any software at all and the configuration is [entirely done with the keyboard](https://higround.co/pages/performancebase65) so I think they will not have bothered exposing any HID interface at all.)
  - [Performance Collection](https://higround.co/collections/performance-collection)

## Keyboard without a usable analogue interface

- Logitech (Firmware [does provide analogue reports](https://gist.github.com/Sainan/0f21e6937ee72b7979ec44ee9fde6016) but unfortunately only for whichever key is being pressed down furthest.)
  - [PRO X TKL RAPID](https://www.logitechg.com/en-gb/products/gaming-keyboards/pro-x-tkl-rapid.html)
- [Keydous](https://keydous.store/collections/magnetic-swich-keyboards) (Firmware [can provide analogue reports](https://gist.github.com/Sainan/488eb9dfecdd863d4e057e8516efd7f3) but they unfortunately only say how far the most recent key is being pressed — not even which key that is.)
  - Keydous NJ98-CP
- Glorious (Don't own this but [looks identical to Keydous](https://github.com/AnalogSense/universal-analog-plugin/issues/1#issuecomment-2558528441))
  - [GMMK PRO 3 HE](https://www.gloriousgaming.com/en-eu/products/gmmk-3-pro-he-prebuilt-keyboard)
- Attack Shark (Don't own this but [looks identical to Keydous](https://github.com/AnalogSense/universal-analog-plugin/issues/1#issuecomment-2692071899))
  - https://attackshark.com/products/attack-shark-x65-he-magnetic-switch-rapid-trigger-keyboard-coiled-cable
- Akko (Firmware [can be asked to provide analogue reports](https://gist.github.com/Sainan/ec06cf65e3bc3a6bf0728c3d4ea79deb), but this also disables digital input.)
  - Akko MOD 007 series
- SteelSeries (Firmware does not seem to expose analogue data.)
  - SteelSeries Apex Pro
- Corsair (Firmware does not seem to expose analogue data.)
  - Corsair K70 with Magnetic Switches

---

If your keyboard is not mentioned here, feel free to open a new issue or post a comment here.

**Comment by MF-JEWM** [comment]
Is there potential of adding support for [Keychron Q1 HE](https://www.keychron.com/products/keychron-q1-he-qmk-wireless-custom-keyboard)?

**Comment by Sainan** [comment]
Hmm, does look promising with the "Keychron Launcher", but it [only being able to display 1 analogue value](https://youtu.be/CUMQUaBqjPg?si=HLT3oCJLqYvUXNVK&t=432) may mean they didn't bother implementing a full interface.

**Comment by MF-JEWM** [comment]
hmm well within the Gamepad Analog tab of Keychron Launcher there is a feature called Joystick Effect Demo and it is able to do both left and right joystick smoothly at the same time. does that mean it might be able to display more than 1 value and currently its purely just a visual limitation of the launcher's UI and not the keyboard itself?

**Comment by Sainan** [comment]
I don't know. I don't own this keyboard. I guess I'll buy one and try it.

**Comment by Sainan** [comment]
@MF-JEWM I've just published universal-analog-plugin version 0.2.2 which features support for the Keychron Q1 HE. I was unfortunately only able to poll analogue values from the keyboard, so compromises had to be made, but I think it's still decently usable. Might be able to do more on this front once they open-source the firmware.

**Comment by MF-JEWM** [comment]
@Sainan I am also really hoping they eventually open-source the firmware for this board. Maybe once things get sorted out with the feature that Razer and Wooting are currently adding to their boards as it appears that feature is currently being pushed to QMK as a whole.

Thanks again for still taking a look at how to integrate the use board 😄

**Comment by CaelTheColher** [comment]
Can you look into the Madlions 60HE?

**Comment by Sainan** [comment]
@CaelTheColher Do you own this keyboard? If so, could you check if the "web driver" has any visualisation that shows how far you are pressing your keys?

**Comment by CaelTheColher** [comment]
There is a calibration setting that does show how far each key is being pressed

**Comment by Sainan** [comment]
Hmm, does the calibration mode disable digital input?

**Comment by CaelTheColher** [comment]
yes, but after saying that I realised that there is also an option that just shows it as a number and doesnt disable inputs
![image](https://github.com/user-attachments/assets/0045ecee-a84f-4dad-9e80-23ce67a984aa)

**Comment by CaelTheColher** [comment]
I'm pretty sure the small number below each key is how far down it is being pressed in mm (in the image I'm fully pressing H and lightly pressing F and G), but no idea about the number on the top

**Comment by Sainan** [comment]
Hmm, okay. Looks like it's the travel distance in mm.

**Comment by Nathan22211** [comment]
what about the hunstman V3? I have one but I'm a linux user so I can't use synapse. wether or not the wooting plugin works without synapse on linux, as wooting supports Linux, I'm not sure of

**Comment by Sainan** [comment]
@Nathan22211 I did look into Razer on Linux, but I think the blocking factor there is lack of analogue keyboard support by the OpenRazer driver because afaict, these keyboards report input either in a digital or analogue format, so when they're switched into the mode where they do report analogue input, they need a driver to synthesise the digital input.

**Comment by Sainan** [comment]
@CaelTheColher Are you sure about that? It looks to me like the travel distance is only being reported during the calibration process, as it justs shows 0.0 otherwise. At least on firmware version 1.03.

**Comment by Sainan** [comment]
@CaelTheColher Well, I did end up managing to figure it out. There is indeed a separate report being used to poll the state. So, I ended up managing to support it by using that. Pretty meh tho because it's really not the greatest way to grab the keyboard state.

**Comment by CaelTheColher** [comment]
I think they updated the web driver it broke the display because now its only showing 0.0 for me too

**Comment by CaelTheColher** [comment]
Since the mad68 isn't supported yet and I don't expect you to buy it just for this, is there anything I can do to help you add support for it?

**Comment by Sainan** [comment]
@CaelTheColher Sure, I think the easiest way would be for you to clone/download <https://github.com/AnalogSense/JavaScript-SDK> and open the demo.html locally, then try to mess around in the AnalogSense.js, currently after line 700:
- Remove the `productId` from the filters so your keyboard can be selected
- Mess around with the `layout` so every key is correctly detected
  - You will notice it's currently 14 keys wide per line/row.

Once you have the correct layout, send it my way.

**Comment by CaelTheColher** [comment]
@Sainan 
```
const layout = [
            /*  0 */ KEY_ESCAPE,    KEY_1,     KEY_2,    KEY_3,    KEY_4,    KEY_5,    KEY_6,     KEY_7,    KEY_8,    KEY_9,     KEY_0,         KEY_MINUS,        KEY_EQUALS,        KEY_BACKSPACE,  KEY_INSERT,
            /* 14 */ KEY_TAB,       KEY_Q,     KEY_W,    KEY_E,    KEY_R,    KEY_T,    KEY_Y,     KEY_U,    KEY_I,    KEY_O,     KEY_P,         KEY_BRACKET_LEFT, KEY_BRACKET_RIGHT, KEY_BACKSLASH,  KEY_DEL,
            /* 28 */ KEY_CAPS_LOCK, KEY_A,     KEY_S,    KEY_D,    KEY_F,    KEY_G,    KEY_H,     KEY_J,    KEY_K,    KEY_L,     KEY_SEMICOLON, KEY_QUOTE,        KEY_NONE,          KEY_ENTER,      KEY_PAGE_UP,
            /* 42 */ KEY_LSHIFT,    KEY_NONE,  KEY_Z,    KEY_X,    KEY_C,    KEY_V,    KEY_B,     KEY_N,    KEY_M,    KEY_COMMA, KEY_PERIOD,    KEY_SLASH,        KEY_RSHIFT,        KEY_ARROW_UP,   KEY_PAGE_DOWN,
            /* 56 */ KEY_LCTRL,     KEY_LMETA, KEY_LALT, KEY_NONE, KEY_NONE, KEY_NONE, KEY_SPACE, KEY_NONE, KEY_NONE, KEY_RALT,  KEY_FN,        KEY_RCTRL,        KEY_ARROW_LEFT,    KEY_ARROW_DOWN, KEY_ARROW_RIGHT
        ];
```

This seems to be the correct layout

**Comment by CaelTheColher** [comment]
I didn't update the comments because I forgot, but its now 15 keys per row

**Comment by Sainan** [comment]
@CaelTheColher Thank you! I've added support for the MAD68HE to everything.

**Comment by mksheffey** [comment]
Can you look into adding the GMMK PRO 3 HE, if it's even at all possible? If there is anything I can do to help, please let me know. Thanks

**Comment by Sainan** [comment]
@mksheffey If you own this keyboard, could you check the companion software if there's anywhere it does show how far you are pressing your keys?

**Comment by mksheffey** [comment]
Of course, I have just checked and the software only shows a cursor displaying how far any key is being pressed down. It doesn't list a numerical value. Here is a ss of the terrible software :( Here is the imgur link : https://imgur.com/4zUmxZR

**Comment by Sainan** [comment]
@mksheffey Okay, that's interesting. While you're in that view, could you try going to https://analogsense.org/webhid-input-report-logger/ and seeing what gets logged as you press keys? That might indicate if the format supports multiple keys.

**Comment by mksheffey** [comment]
@Sainan After doing so alotta random numbers are showing up on the webpage. When pressing one key, almost 6 or 7 numbers show afterwards.

**Comment by Sainan** [comment]
Haha, great. Could you press, for example A, then D while still holding down A, and then give me the log?

**Comment by mksheffey** [comment]
@Sainan Here goes. 
[GMMK PRO 3 HE A& D.txt](https://github.com/user-attachments/files/18222696/GMMK.PRO.3.HE.A.D.txt)

**Comment by Sainan** [comment]
Yeah, that does unfortunately look like it doesn't say which key is being pressed, only how far. The report format seems identical to Keydous.

**Comment by mksheffey** [comment]
Aww dang, thats unfortunate. Well thanks for helping out.

**Comment by hadono1** [comment]
Hello! Besides the layout, is there anything else you'd need to add support for the AS x65HE?

**Comment by hadono1** [comment]
Hello! Is it possible to add support for the Attack Shark x65he?
Seeing what you've asked others above, I'll provide that info for this keeb too.
Firstly, there is an option in the driver to view how far the key is being pressed, but not as a numerical value, only visual. Also, it says that the keyboard may not work until that option is disabled, but that isn't the case at all, digital inputs still work while it is enabled. https://imgur.com/a/nuq7FBR
On the website  https://analogsense.org/webhid-input-report-logger/ , here's the input I got when pressing a, s, d, then releasing them in the same order: [ASx65he inputs.txt](https://github.com/user-attachments/files/19037949/ASx65he.inputs.txt)

**Comment by Sainan** [comment]
That report format does look familiar. It's the same as what we've observed with Keydous and Glorious, which is unfortunately not conducive to usage for analog input.

**Comment by hadono1** [comment]
Are you sure? The integers have a different format for different keys ('a' has that 09 meanwhile 's' has that 0f, they also work independently of which one is pressed further(unlike the pro x tkl). There's just a lot more inputs per keypress compared to the GMMK PRO 3 HE (probably because of the higher scanrate? Idk about the GMMK but AS has a 128k scan rate on this keeb)
Edit: added the scanrate info

**Comment by Sainan** [comment]
Well, the mapping of the keys is irrelevant. The report has the same `1B` prefix and it also only contains a single key. It doesn't matter if that key is the furthest pressed or whatever. The important factor is that you can only have an analogue reading of a singular key.

**Comment by hadono1** [comment]
How does it look for multiple keys? I am genuinely curious.

**Comment by Sainan** [comment]
When you press multiple keys, the analogue report only contains a single key. That's the problem.

**Comment by hadono1** [comment]
so it's supposed to contain data about both keypresses in the same integer value?

**Comment by hadono1** [comment]
Nvm, after taking a look at [keydous-analogue-reports.cpp](https://gist.github.com/Sainan/488eb9dfecdd863d4e057e8516efd7f3#file-keydous-analogue-reports-cpp), now I get what you're saying. Thanks anyway for confirming that this keeb ain't gon work unfortunately.

**Comment by Azarattum** [comment]
@Sainan, would it be difficult to support the new Keychron Lemokey P1 HE? Official firmware support was added here https://github.com/Keychron/qmk_firmware/commit/b21fc4a15c35225eae9de0532fcefdfd3fdd91c0. The [analog_matrix.c](https://github.com/Keychron/qmk_firmware/blob/b21fc4a15c35225eae9de0532fcefdfd3fdd91c0/keyboards/lemokey/common/analog_matrix/analog_matrix.c) looks similar to Keychron Q series.

**Comment by Azarattum** [comment]
I've figured out the layout and copied the vendor/product ID from the firmware. Here is my PR for JS SDK https://github.com/AnalogSense/JavaScript-SDK/pull/5

**Comment by Azarattum** [comment]
@Sainan sorry to nudge you, but could with release a build (just Linux and Windows for now) with the recent Lemokey changes, so I can test it out?

**Comment by Sainan** [comment]
@Azarattum If Windows is okay, then I can offer you this: [Windows.zip](https://github.com/user-attachments/files/19222890/Windows.zip)

**Comment by Azarattum** [comment]
Yeah Windows is okay, thank you!

**Comment by Azarattum** [comment]
@Sainan, wooting-analog-sdk seem to freeze in an infinite loop when using the universal-analog-plugin with the keyboard connected. I've tested with wooting-analog-midi and Cyberpunk, both freeze even before the window is open. Analyzing USB traffic with wireshark, you can see that the SDK asks for the version, keyboard answers, then nothing...

_host -> keyboard_:
```hex
0000   1b 00 10 30 73 89 8f b5 ff ff 00 00 00 00 09 00   ...0s...........
0010   00 08 00 03 00 02 01 20 00 00 00 a9 01 00 00 00   ....... ........
0020   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
0030   00 00 00 00 00 00 00 00 00 00 00                  ...........

0000   1b 00 10 30 73 89 8f b5 ff ff 00 00 00 00 09 00   ...0s...........
0010   01 08 00 03 00 02 01 00 00 00 00                  ...........
```

_keyboard -> host_:
```hex
0000   1b 00 10 d0 3a 8b 8f b5 ff ff 00 00 00 00 09 00   ....:...........
0010   01 08 00 03 00 82 01 20 00 00 00 a9 01 04 00 00   ....... ........
0020   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
0030   00 00 00 00 00 00 00 00 00 00 45                  ..........E

0000   1b 00 10 d0 3a 8b 8f b5 ff ff 00 00 00 00 09 00   ....:...........
0010   00 08 00 03 00 82 01 00 00 00 00                  ...........
```

Web demo works fine, here are the same version packets from it:
_host -> keyboard_:
```hex
0000   1b 00 20 ba de 8e 8f b5 ff ff 00 00 00 00 09 00   .. .............
0010   00 08 00 03 00 02 01 20 00 00 00 a9 01 00 00 00   ....... ........
0020   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
0030   00 00 00 00 00 00 00 00 00 00 00                  ...........

0000   1b 00 20 ba de 8e 8f b5 ff ff 00 00 00 00 09 00   .. .............
0010   01 08 00 03 00 02 01 00 00 00 00                  ...........
```

_keyboard -> host_:
```hex
0000   1b 00 a0 05 51 88 8f b5 ff ff 00 00 00 00 09 00   ....Q...........
0010   01 08 00 03 00 82 01 20 00 00 00 a9 01 04 00 00   ....... ........
0020   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
0030   00 00 00 00 00 00 00 00 00 00 45                  ..........E

0000   1b 00 a0 05 51 88 8f b5 ff ff 00 00 00 00 09 00   ....Q...........
0010   00 08 00 03 00 82 01 00 00 00 00                  ...........
```

And then it goes on polling with `a9 31` as expected. Any idea why could that be? Does the wooting-analog-sdk expect something more from the keyboard? (that would explain the freeze).

[Here are](https://github.com/user-attachments/files/19259119/pcap.zip) the traffic dumps for both web and sdk. You can filter both by `usb.src == 8.3.2 || usb.dst == 8.3.2` to see relevant packets.

**Comment by Azarattum** [comment]
I have also tried with the stock firmware (without the full analog report patch). The result is exactly the same (except the version now doesn't have the `0x45` marker). It freezes after the version packet. Are there any logs or other helpful info I can provide?

**Comment by Azarattum** [comment]
I've also tried using `.\soup.exe keyboard`. It doesn't work as well. Behaves exactly the same: version packet, response then nothing... 

[Here are the dumps](https://github.com/user-attachments/files/19259259/pcap2.zip) for soup and stock firmware tests.

**Comment by kartavkun** [comment]
Hey! What about Aula Win60HE?

**Comment by skurukulasuriya** [comment]
Can you look into Ajazz AK680 MAX? In their software it is possible to see how much the key is being pressed. I really want some open source customization for this keyboard. If it's doable I can help you to add support to it. I suspect it might only reveal the position of the last pressed key. But is there some way around it?

**Comment by skurukulasuriya** [comment]
> yes, but after saying that I realised that there is also an option that just shows it as a number and doesnt disable inputs ![image](https://github.com/user-attachments/assets/0045ecee-a84f-4dad-9e80-23ce67a984aa)

I found similar functionality within their software. I guess it's possible to read the analog values in a way that is similar to mad60 he?

https://github.com/user-attachments/assets/cfc58314-4c0f-4b9f-a463-78c4fe38c473

**Comment by chuckythecat** [comment]
> I found similar functionality within their software. I guess it's possible to read the analog values in a way that is similar to mad60 he?

@skurukulasuriya Does this disable digital inputs? Can you still type with this mode enabled?

**Comment by eloabu7-oss** [comment]
Hello! Hope you're doing good.
I recently saw that the Aula Win60he can report travel distance, is there any posibilities that this keyboard will work? 

<img width="1542" height="835" alt="Image" src="https://github.com/user-attachments/assets/59260de7-6333-4420-881b-c0b97328d4de" />

**Comment by XzenooZ** [comment]
Hello, hope you take a look into this. Im gonna bump that ajazz ak680 max, the keyboard is working with " https://[analogsense.org/webhid-input-report-logger/](https://analogsense.org/webhid-input-report-logger/) " and has a demonstration in its drivers. 

https://github.com/user-attachments/assets/dc950514-d3e6-412a-b9a5-664dcd3bc6db

If you need more info I can be able to help, thanks.

**Comment by pc49a** [comment]
Is monsgeeks fun60 ultra tmr possible for support?

**Comment by tnynyn** [comment]
Got an Akko Tac75 HE, any chance it can be added?

pic from their custom switch settings:

<img width="1565" height="809" alt="Image" src="https://github.com/user-attachments/assets/b902f260-4028-4d14-869c-c42eff8ccd4b" />

**Comment by Parsdam** [comment]
<img width="1250" height="688" alt="Image" src="https://github.com/user-attachments/assets/8691bfe5-4bb2-441a-9de3-e7652a816f5e" /> wraith w75 analog plsssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss the v1 version
