### ISSUE TITLE
Huntsman V2 Analog Does not Work With GTA SA using Wooting GInput

### ISSUE THREAD

**Issue by CommandGenius** [calamity-inc/universal-analog-plugin#5]

**Comment by Sainan** [comment]
Could you share details on what you mean by "Wooting GInput"?

**Comment by Sainan** [comment]
Okay, I did manage to locate a download link thanks to hunting through old forums threads and viewing dead pages on web.archive.org.

It looks like it ships with [the old analogue SDK](https://github.com/WootingKb/wooting-analog-sdk-old) that was still written in C. From what I can tell in IDA, it only supports the original Wooting One with unupdated firmware, so this "Wooting GInput" is practically unusable nowadays unless this API is replaced/updated.

**Comment by Sainan** [comment]
This should help you get it working, just have to replace the `wooting-analog-sdk.dll`: https://github.com/AnalogSense/old-wooting-analog-sdk-shim

**Comment by CommandGenius** [comment]
> This should help you get it working, just have to replace the `wooting-analog-sdk.dll`: https://github.com/AnalogSense/old-wooting-analog-sdk-shim

This makes my game lag like crazy and random inputs appear ingame.

**Comment by Sainan** [comment]
Sorry, I didn't test it specifically with the Razer Huntsman. Should be working fine now.
